/*
 * janja API
 *
 * Janja accounts API endpoints featuring core actions such as user authentication, user creation,
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VerifyphoneVerifysmsBody struct {

	Number string `json:"number,omitempty"`

	Code string `json:"code,omitempty"`
}
