/*
 * janja API
 *
 * Janja accounts API endpoints featuring core actions such as user authentication, user creation,
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NewUserObject struct {

	Email string `json:"email,omitempty"`

	Phone string `json:"phone,omitempty"`

	Password string `json:"password,omitempty"`
}
