/*
 * janja API
 *
 * Janja accounts API endpoints featuring core actions such as user authentication, user creation,
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AuthSendemailBody struct {

	Subject string `json:"subject,omitempty"`

	Body string `json:"body,omitempty"`

	RecipientList []Object `json:"recipient_list,omitempty"`

	EmailerName string `json:"emailer_name,omitempty"`
}
