/*
 * janja API
 *
 * Janja accounts API endpoints featuring core actions such as user authentication, user creation,
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/jackkweyunga/janja-api/1.0.0/",
		Index,
	},

	Route{
		"ApiV1AuthLoginPost",
		strings.ToUpper("Post"),
		"/jackkweyunga/janja-api/1.0.0/api/v1/auth/login",
		ApiV1AuthLoginPost,
	},

	Route{
		"ApiV1AuthLogoutPost",
		strings.ToUpper("Post"),
		"/jackkweyunga/janja-api/1.0.0/api/v1/auth/logout",
		ApiV1AuthLogoutPost,
	},

	Route{
		"ApiV1AuthSendEmailPost",
		strings.ToUpper("Post"),
		"/jackkweyunga/janja-api/1.0.0/api/v1/auth/send-email",
		ApiV1AuthSendEmailPost,
	},

	Route{
		"ApiV1AuthSendOtpPost",
		strings.ToUpper("Post"),
		"/jackkweyunga/janja-api/1.0.0/api/v1/auth/send-otp",
		ApiV1AuthSendOtpPost,
	},

	Route{
		"ApiV1AuthVerifyPhoneSendSmsPost",
		strings.ToUpper("Post"),
		"/jackkweyunga/janja-api/1.0.0/api/v1/auth/verify-phone/send-sms",
		ApiV1AuthVerifyPhoneSendSmsPost,
	},

	Route{
		"ApiV1AuthVerifyPhoneVerifySmsPost",
		strings.ToUpper("Post"),
		"/jackkweyunga/janja-api/1.0.0/api/v1/auth/verify-phone/verify-sms",
		ApiV1AuthVerifyPhoneVerifySmsPost,
	},

	Route{
		"ApiV1UsersInitPost",
		strings.ToUpper("Post"),
		"/jackkweyunga/janja-api/1.0.0/api/v1/users/init/",
		ApiV1UsersInitPost,
	},

	Route{
		"GetLoggedInUser",
		strings.ToUpper("Get"),
		"/jackkweyunga/janja-api/1.0.0/api/v1/users/me",
		GetLoggedInUser,
	},
}
